--exec InsertCustomer
--exec InsertSupplier
--exec InsertCategory
--exec InsertProduct
--exec InsertOnlineOrder
--exec InsertStaff
--exec InsertOfflineOrder
--drop procedure InsertStaff
--DELETE FROM [Staff]
--WHERE id = 1;
--exec InsertRecordDay
--exec EtlSupplier
--drop procedure EtlSupplier
--exec EtlOrder
--drop procedure ETL_ImportOrder
--exec EtlUser 
drop procedure EtlUser